global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'antifraud-service'
    static_configs:
      - targets: ['antifraud-service:8000']

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']